### ISSUE TITLE
monasca datasource keystone properties not exported/imported via api

### ISSUE THREAD

**Issue by ghost** [rbak1/grafana-plugins#3]
if i query the datasources via api:

curl -s "http://username:password@grafana-hostname:3000/api/datasources"

then the monasca datasources do not return the keystone specific properties like "keystone enabled" or "token". the same applies in the other direction, if i want to create a monasca datasource via api, i can't set the keystone properties, as they get ignored.

tested at least on the 2.6.0-keystone branch

**Comment by rbak** [comment]
If you query a brand new monasca datasource without setting keystoneAuth or token, that information won't appear in the results of you datasource list. Try setting those through the gui, and then doing a get to confirm they are set.

For creating them through the api those special fields are in a jsonData hash. e.g.
`{
    "name": "Monasca",
    "type": "monasca",
    "url": "http://monasca-endpoint:8070",
    "access": "proxy",
    "isDefault": true,
    "jsonData": {
        "keystoneAuth": true
    }
}`

If you're still having issues let me know.

**Comment by ghost** [comment]
i think we should reopen this one: i just checked your above suggestion (i missed the jsonData around the keystoneAuth property) and it really works, but if i afterwards query the datasources it gives me "jsonData":null for this just properly added datasource with keystone auth, so looks like this jsondata is not exported properly at aleast.

**Comment by rbak** [comment]
I can't seem to replicate your problem.  When I do a 'get' on the datasource using the api, I see the jsonData I would expect.  Can you provide a little more information on your call and maybe what version of Grafana you're using?

**Comment by ghost** [comment]
the call to get the datasources via api i'm using is:

  curl https://admin-user:admin-password@grafana-server/api/datasources

the the grafana + plugins are the current state of
https://github.com/sapcc/grafana - 5c13d4e
https://github.com/sapcc/grafana-plugins - e1ff528

which should be nearly in sync to your keystone 2.6.0-keystone branch (i'll recheck with darran hague to make sure). a monasca datasource queries this way looks like:

{
    "jsonData": null,
    "isDefault": true,
    "withCredentials": false,
    "basicAuthPassword": "",
    "basicAuthUser": "",
    "basicAuth": false,
    "database": "",
    "id": 5,
    "orgId": 1,
    "name": "monasca",
    "type": "monasca",
    "access": "proxy",
    "url": "http://monasca-api:8080",
    "password": "",
    "user": ""
  }

which has json data null, although keystone auth is enabled in the datasource. creating such a datasource via api works fine, even with json data. in case you can't reproduce the problem with current code, we should recheck after syncing to your latest code i would suggest.

**Comment by rbak** [comment]
This is just a property of the api, and not in the control of the datasource plugin.  Listing resources (datasources, dashboards, etc.) will only give you top level information about the resource.  If you want the full json you'll need to query /api/datasources/<datasource id>

**Comment by ghost** [comment]
you are right - this way it works fine - thanks for clarification - all fine now :)
